target 'ComicCards' do
  inhibit_all_warnings!
  use_frameworks!

  pod 'Moya'
  pod 'Kingfisher'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
