
platform :ios, '11.0'

target 'PhotoTagger' do
  inhibit_all_warnings!
  use_frameworks!

  # Pods for PhotoTagger
  pod 'Alamofire', '~> 4.7.0'
  pod 'SwiftyJSON', '~> 4.0.0'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
